### PR TITLE
chore: update highs and emsdk

### PR DESCRIPTION
**Pull request by RebeccaStevens**
As HiGHS is being updated, I believe this would be a breaking change.

### CODE REVIEW

**Comment by lovasoa** [comment]
@RebeccaStevens , can you have a look at the failing tests ?

**Comment by RebeccaStevens** [comment]
I've updated the tests for the newer version of HiGHS, but `isLinear` is always returning `false`.

This line may need to be updated, but I'm not sure what the new criteria is: https://github.com/lovasoa/highs-js/blob/6ad065d8560d39afd59d998afc736a38d25896cc/src/post.js#L172

@lovasoa As you're much more familiar with HiGHS than me, would you be able to look into this?

**Comment by lovasoa** [comment]
Hi, sorry, I don't really have the time to look at it right now.

We knew parsing the text output of highs was fragile, but did not find another way to get the information we needed at the time. 


You should be able to find how to get the information of whether the problem is linear or quadratic in highs documentation. If you don't, maybe ask someone from the highs project. Maybe @jajhall ?

**Comment by jajhall** [comment]
> You should be able to find how to get the information of whether the problem is linear or quadratic in highs documentation. If you don't, maybe ask someone from the highs project. Maybe @jajhall ?

- Highs::getModel().isQp()
- Highs::getModel().isMip()

return bool

**Comment by RebeccaStevens** [comment]
@jajhall That seems easy enough. However, I'm not very familiar with emsdk and how it works to wrap HiGHS; so I don't actually know how to call those functions.

@lovasoa This is probably a bit too much of a learning curve for me to fix this anytime soon. I might need someone else to take over this PR.

**Comment by lovasoa** [comment]
closed by https://github.com/lovasoa/highs-js/pull/35

**Pull request closed without merging**
